apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/salaboy/s1p-gateway:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/salaboy/s1p-gateway:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: s1p-gateway
        chartPath: charts/s1p-gateway
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/salaboy/s1p-gateway"
          image.tag: "{{.TAG}}"
